---
- hosts: all 
  become: true 
  tasks:
  - name: template execution
    template:
      src: temp1.j2
      dest: /home/ansible/temp1
  - name: tomcat7 default settings
    template:
      src: tomcat7.j2
      dest: /etc/default/tomcat7
    notify: